#### Basic Operations and Arrays

- Python NumPy Basic

59. Element-Wise Multiply Two Arrays

In [139]:
import numpy as np

In [3]:
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])

nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])

print(nums1 * nums2)

[[10 15  8]
 [ 3 10 25]]


- Python NumPy arrays

205. Compute weight sum of rows where names match a condition.

In [30]:
student = np.array([
    ['01', 'V', 'Debby Pramod', 30.21],
    ['02', 'V', 'Artemiy Ellie', 29.32],
    ['03', 'V', 'Baptist Kamal', 31.00],
    ['04', 'V', 'Lavanya Davide', 30.22],
    ['05', 'V', 'Fulton Antwan', 30.21],
    ['06', 'V', 'Euanthe Sandeep', 31.00],
    ['07', 'V', 'Endzela Sanda', 32.00],
    ['08', 'V', 'Victoire Waman', 29.21],
    ['09', 'V', 'Briar Nur', 30.00],
    ['10', 'V', 'Rose Lykos', 32.00]
])

res = student[np.char.startswith(student[:, 2], 'E')]
res[:, 3].astype(float).sum()

np.float64(63.0)

#### Mathematics, Linear Algebra, and Statistics

##### Python NumPy Mathematics

40. Write a NumPy program to compute xy, element-wise where x, y are two given arrays.

In [38]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

print(np.power(x,y))

[[ 1  4]
 [ 3 16]]


41. Write a NumPy program to compute an element-wise indication of the sign for all elements in a given array.

In [39]:
x = np.array([1, 3, 5, 0, -1, -7, 0, 5])
print(np.sign(x))

x[x > 0] = 1
x[x < 0] = -1
print(x)

[ 1  1  1  0 -1 -1  0  1]
[ 1  1  1  0 -1 -1  0  1]


4. Write a NumPy program to compute the determinant of a given square array.

In [40]:
a = np.array([[1, 0], [1, 2]])
print(np.linalg.det(a))

2.0


15. Write a NumPy program to compute the sum of the diagonal element of a given array.

In [43]:
a = np.array([[3, 0], [1, 2]])
print(np.trace(a))

5


##### Python NumPy Statistics

1. Write a Python program to find the maximum and minimum value of a given flattened array.

In [53]:
arr = np.arange(1, 10).reshape(3,3)
print(arr)

print(arr.max())
print(arr.min())

print(arr.max(axis=1))
print(arr.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[3 6 9]
[1 4 7]


7. Write a NumPy program to compute the mean, standard deviation, and variance of a given array.

In [60]:
arr = np.arange(6)

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

2.5
2.5
1.707825127659933
2.9166666666666665


13. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

In [54]:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7]

print(np.bincount(array1))

[1 3 2 0 1 0 1 1]


#### Random Numbers

2. Write a NumPy program to generate six random integers between 10 and 30.

In [129]:
np.random.rand(3,2)

array([[0.87805154, 0.58076728],
       [0.00304339, 0.15922514],
       [0.18434846, 0.66846677]])

In [130]:
print(np.random.randint(low=10, high=30, size=6))

[11 26 25 24 24 12]


15. Write a NumPy program to find the closest value (to a given scalar) in an array.

In [132]:
arr = np.arange(50)
target = np.random.uniform(low=0, high=50)
print('Target:',target)

np.random.shuffle(arr)

index = np.abs(arr-target).argmin()
print('Result: ',arr[index])

Target: 48.3218707450584
Result:  48


#### Sorting, Searching, and Indexing

##### Python NumPy Sorting and Searching

1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [133]:
a = np.array([[4,1], [3,2]])

print("Original array:")
print(a)

print("Sort the array along the first axis:")
print(np.sort(a, axis=0))

print("Sort the array along the last axis:")
print(np.sort(a))

print("Sort the flattened array:")
print(np.sort(a, axis=None)) 

Original array:
[[4 1]
 [3 2]]
Sort the array along the first axis:
[[3 1]
 [4 2]]
Sort the array along the last axis:
[[1 4]
 [2 3]]
Sort the flattened array:
[1 2 3 4]


3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

In [134]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]

students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students = np.array(students_details, dtype=data_type)

print("Original array:")
print(students)

print("Sort by class, then height if class are equal:")
print(np.sort(students, order=['class', 'height'])) 

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by class, then height if class are equal:
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


5. Write a NumPy program to get the indices of the sorted elements of a given array.
Expected Output:

In [135]:

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

print(student_id)

i = np.argsort(student_id)
print(i) 

[1023 5202 6230 1671 1682 5241 4532]
[0 3 4 6 1 5 2]


8. Write a  NumPy program to sort the specified number of elements from beginning of a given array.

In [138]:
nums = np.random.rand(10)

print("Original array:")
print(nums)

print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums, range(5))]) 

Original array:
[0.4587683  0.95842589 0.47710996 0.99651458 0.86220166 0.99233671
 0.9611976  0.58666763 0.27417644 0.06115235]

Sorted first 5 elements:
[0.06115235 0.27417644 0.4587683  0.47710996 0.58666763 0.99233671
 0.9611976  0.86220166 0.95842589 0.99651458]


##### NumPy Advanced Indexing

20. Write a NumPy program that creates a 2D NumPy array and uses a mask array (boolean array) for indexing to select a subset of elements that match the mask criteria

In [143]:
arr = np.random.randint(low=1, high=50, size=(5,5))
print(arr)

[[45 35 22 27 47]
 [22  7 48 43 37]
 [29 28 22  2  6]
 [26 14  2 13 17]
 [ 7 36 47 17 18]]


In [146]:
new_arr = arr%2 ==0
print(new_arr)

print(arr[new_arr])

[[False False  True False False]
 [ True False  True False False]
 [False  True  True  True  True]
 [ True  True  True False False]
 [False  True False False  True]]
[22 22 48 28 22  2  6 26 14  2 36 18]


#### Datetime and String Operations

##### Python NumPy DateTime

1. Write a  NumPy program to display all the dates for the month of Jan, 2025.

In [149]:
np.arange('2025-01', '2025-02', dtype='datetime64[D]')

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
       '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
       '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
       '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
       '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
       '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28',
       '2025-01-29', '2025-01-30', '2025-01-31'], dtype='datetime64[D]')

2. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [150]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ", yesterday)

today = np.datetime64('today', 'D')
print("Today: ", today)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow) 

Yestraday:  2025-01-12
Today:  2025-01-13
Tomorrow:  2025-01-14


##### Python NumPy String

- 1. Write a NumPy program to concatenate element-wise two arrays of string.

In [152]:
x1 = np.array(['Python', 'PHP'])
x2 = np.array([' Java', ' C++'])

x1 + x2

array(['Python Java', 'PHP C++'], dtype='<U11')

22. Write a NumPy program to split a given text into lines and split the single line into array values.

In [157]:
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""

print("Original text:") 
print(student)

Original text:
01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos


In [158]:
text_lines = [r.split('\t') for r in student.splitlines()]

result = np.array(text_lines)
print(result) 

[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]


#### Broadcasting and Memory Layout

20. Write a NumPy program that Multiplies each column of a 2D array x of shape (7, 3) by a 1D array y of shape (7,) using broadcasting.

In [159]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12],
              [13, 14, 15],
              [16, 17, 18],
              [19, 20, 21]])

y = np.array([1, 2, 3, 4, 5, 6, 7])

In [168]:
y[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [169]:
x * y[:, np.newaxis]

array([[  1,   2,   3],
       [  8,  10,  12],
       [ 21,  24,  27],
       [ 40,  44,  48],
       [ 65,  70,  75],
       [ 96, 102, 108],
       [133, 140, 147]])

##### NumPy Memory Layout

3. Write a NumPy program to create a 2D array of shape (4, 4), then use ravel() to flatten it and print the result.

In [175]:
arr = np.arange(1,17).reshape(4,4)
print(arr)

arr1 = arr.ravel()
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


14. Write a NumPy program that creates a 2D array of shape (4, 5) and use flatten(order='C') and flatten(order='F'). Print both flattened arrays.

In [181]:
arr = np.arange(1,21).reshape(4,5)
print(arr)

print(arr.flatten(order='C'))
print(arr.flatten(order='F'))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20]


19. Write a NumPy program that creates a 1D array of 20 elements and use reshape() to create a (4, 5) matrix. Slice a (2, 3) sub-matrix and print its strides.

In [190]:
arr = np.arange(20).reshape(4,5)

print(arr)

print('\n', arr[:2,:3])
print('\n', arr[:2,:3].strides)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

 [[0 1 2]
 [5 6 7]]

 (40, 8)


#### Performance Optimization and Interoperability

##### NumPy Performance Optimization

20. Write a NumPy program that creates a large NumPy array and write a function to reverse its elements using a for loop. Optimize it using NumPy's slicing operations.

In [203]:
import time
arr = np.random.randint(1,10000,size=10000)
print(arr)

t1 = time.time()
rev_arr = np.empty_like(arr)
for i in range(len(arr)):
    rev_arr[i] = arr[len(arr) - i - 1]
print('Loop: ',time.time() - t1)

t2 = time.time()
print(arr[::-1])
print('Slicing: ',time.time()-t2)


[6061 7079 4028 ... 4554 3310 5019]
Loop:  0.014192581176757812
[5019 3310 4554 ... 4028 7079 6061]
Slicing:  0.00060272216796875


##### NumPy Interoperability

20. Write a NumPy program to append a NumPy array to a Python list and print the result.

In [204]:
python_list = [1, 2, 3]
print("Original Python list:",python_list)
print(type(python_list))

numpy_array = np.array([4, 5, 6])
print("\nOriginal NumPy list:",numpy_array)
print(type(numpy_array))

combined_list = python_list + numpy_array.tolist()
print("\nCombined list:")
print(combined_list)
print(type(combined_list))

Original Python list: [1, 2, 3]
<class 'list'>

Original NumPy list: [4 5 6]
<class 'numpy.ndarray'>

Combined list:
[1, 2, 3, 4, 5, 6]
<class 'list'>


#### Input/Output (I/O) Operations

2. Write a NumPy array with both numeric and string data to a CSV file.

In [205]:
data_array = np.array([
    [1, 'Jorah Liina', 95.5],
    [2, 'Basil Aisha', 90.0],
    [3, 'Helga Myrthe', 80.0],
    [4, 'Lehi Piero', 91.5]
], dtype=object)

In [206]:
import csv

with open('./numpy_data.csv', 'w') as f:
    writer = csv.writer(f)
    for i in data_array:
        writer.writerow(i)

In [211]:
from_csv_to_numpy = np.genfromtxt('./numpy_data.csv', delimiter=',', dtype=str)
from_csv_to_numpy

array([['1', 'Jorah Liina', '95.5'],
       ['2', 'Basil Aisha', '90.0'],
       ['3', 'Helga Myrthe', '80.0'],
       ['4', 'Lehi Piero', '91.5']], dtype='<U12')

#### Functions and Masked Arrays

6. Write a NumPy program that uses the np.where ufunc to create a new array from two existing arrays based on a condition applied to a third array.

In [216]:
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([10, 20, 30, 40, 50])
condition_array = np.array([True, False, True, False, True])

result_array = np.where(condition_array, array_1, array_2)

print('Array 1:\n', array_1)
print('Array 2:\n', array_2)
print('Condition array:\n', condition_array)
print('Resulting array using np.where:\n', result_array)

Array 1:
 [1 2 3 4 5]
Array 2:
 [10 20 30 40 50]
Condition array:
 [ True False  True False  True]
Resulting array using np.where:
 [ 1 20  3 40  5]


7. Write a NumPy program that creates a custom ufunc that computes x^2 + 2x + 1 for each element in a NumPy array.

In [221]:
def compute_expression(x):
    return x**2 + 2*x + 1

compute_ufunc = np.frompyfunc(compute_expression, 1, 1)

array_1d = np.array([1, 2, 3, 4, 5])

result_array = compute_ufunc(array_1d)

print('Original 1D array:', array_1d)
print('Result: ', result_array)

Original 1D array: [1 2 3 4 5]
Result:  [4 9 16 25 36]


17. Write a NumPy program that creates an array with NaN values and uses np.nan_to_num to replace NaN with a specified number.

In [224]:
arr = np.array([10, 20, np.nan, 30, np.nan])
print(arr)

res = np.nan_to_num(arr, nan=111)
print(res)

[10. 20. nan 30. nan]
[ 10.  20. 111.  30. 111.]


##### NumPy Masked Arrays

20. Write a NumPy program that creates a masked array and checks if any masked elements are present.

In [235]:
arr = np.random.randint(low=1, high=50, size=(3,3))
print(arr)

cond = arr > 20

new_arr = np.ma.masked_array(arr, mask=cond)
print(new_arr)

has_ele = new_arr.mask.any()

print(has_ele)

[[47 41 43]
 [ 9 28 19]
 [11 24 49]]
[[-- -- --]
 [9 -- 19]
 [11 -- --]]
True


### Structured Arrays and SciPy Integration

##### NumPy Structured Arrays

1. Write a NumPy program that creates a structured array with fields for 'name' (string), 'age' (integer), and 'height' (float). Populate it with sample data for five individuals.

In [241]:
dtypes = [('name', 'U10'), ('age', 'i4')]

arr = np.array([
    ('Meet', 20),
    ('Jay', 21),
    ('Person1', 5),
    ('Person2', 10),
    ('Person3', 15),
], dtype=dtypes)

print(arr)

[('Meet', 20) ('Jay', 21) ('Person1',  5) ('Person2', 10) ('Person3', 15)]


2. Write a NumPy program that accesses and prints all values of the 'Name' field from the structured array created in exercise.

In [242]:
names = arr['name']
print(names)

['Meet' 'Jay' 'Person1' 'Person2' 'Person3']


6. Write a NumPy program that sorts the structured array created with fields for 'name' (string), 'age' (integer), and 'height' (float), by the 'age' field in ascending order and prints the sorted array.

In [248]:
sorted_arr = np.sort(arr, order='age')
print(sorted_arr)

[('Person1',  5) ('Person2', 10) ('Person3', 15) ('Meet', 20) ('Jay', 21)]


##### NumPy Integration with SciPy

1. Write a NumPy program that creates a NumPy array of random numbers and uses SciPy to compute the statistical properties (mean, median, variance) of the array.

In [263]:
from scipy import stats

data = np.random.rand(10)

print(data.mean())
print(stats.tmean(data))
print(np.median(data))
print(stats.tvar(data))

0.5200833279546222
0.5200833279546222
0.5113605610543159
0.08371422948099916


### Advanced Topics and Mastery

#### Advanced NumPy

3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [275]:
arr = np.random.randint(1,10,(4,4))
print(arr)

print(np.sum(arr, axis=1))

[[7 6 9 7]
 [8 1 4 2]
 [3 6 5 3]
 [4 5 8 4]]
[29 15 17 21]


9. Write a NumPy program to create a 5x5 array with random values and sort each row

In [276]:
print(arr)
row_sort = np.sort(arr, axis=1)
print('\n',row_sort)

[[7 6 9 7]
 [8 1 4 2]
 [3 6 5 3]
 [4 5 8 4]]

 [[6 7 7 9]
 [1 2 4 8]
 [3 3 5 6]
 [4 4 5 8]]


11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.

In [277]:
print(arr)

second_largest = np.partition(arr, -2, axis=1)[:,-2]

print(second_largest)

[[7 6 9 7]
 [8 1 4 2]
 [3 6 5 3]
 [4 5 8 4]]
[7 4 5 5]


32. Write a NumPy program to create a 4x4 array with random values and shift all elements one position downwards.

In [284]:
print(arr,'\n')

shifted_arr = np.roll(arr, shift=1, axis=0)
print(shifted_arr)

[[7 6 9 7]
 [8 1 4 2]
 [3 6 5 3]
 [4 5 8 4]] 

[[4 5 8 4]
 [7 6 9 7]
 [8 1 4 2]
 [3 6 5 3]]


#### Mastering NumPy

100. Create a 2D array with random integers and replace all values greater than a certain threshold with that threshold.

In [286]:
arr = np.random.randint(1,100,(5,5))
print(arr, '\n')

th = 50

arr[arr > th] = th
print(arr)

[[ 6 76 25 88 18]
 [39 83 56 43 90]
 [58 96 58 63  4]
 [57 50 67 91 97]
 [64 46 50 32 54]] 

[[ 6 50 25 50 18]
 [39 50 50 43 50]
 [50 50 50 50  4]
 [50 50 50 50 50]
 [50 46 50 32 50]]
